In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# %cd MyDrive
%cd /content/drive/MyDrive/RACL_self

/content/drive/.shortcut-targets-by-id/1tg6xht7UamwA6LK1Pf8GxHN_bBH02xFh/RACL_self


In [2]:
# %cd /content/drive/MyDrive/"2021 봄학기"/"CS475 자연언어처리를 위한 기계학습"/Project/RACL_self
%tensorflow_version 1.x
%pip install \
numpy \
scikit-learn \
tf_slim \
gast==0.2.2
import tensorflow
print(tensorflow.__version__)


TensorFlow 1.x selected.
     |████████████████████████████████| 358kB 7.4MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp37-none-any.whl size=7557 sha256=4d7f8a85b378bc4d3ffb1d9631fc89bd9f92de8ab8caa44dade9b7c97b5d9611
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: kapre 0.3.5 has requirement tensorflow>=2.0.0, but you'll have tensorflow 1.15.2 which is incompatible.
  Found existing installation: gast 0.4.0
    Uninstalling gast-0.4.0:
      Successfully uninstalled gast-0.4.0
1.15.2


In [32]:
import tensorflow as tf
import numpy as np
def get_one_hot(targets, nb_classes):
        res = np.eye(nb_classes)[np.array(targets).reshape(-1)]
        return res.reshape(list(targets.shape)+[nb_classes])
c = tf.math.softmax([[[ 0.5920745,  -0.28320658, -0.5829943 ],
 [ 0.6626713,  -0.31611645, -0.6807799 ],
 [ 0.6591772,  -0.3069582,  -0.674636  ],
 [ 0.,  0.,  0.],
 [ 0.,  0.,  0.]
 [ 0.,  0.,  0.]]], axis=-1).eval(session=tf.compat.v1.Session())
print(c)
d = np.argmax(c, axis=-1)
print(d)
e = get_one_hot(d, 3)
print(e)

[[[0.57952785 0.24151525 0.17895688]
  [0.6109819  0.22958642 0.15943177]
  [0.60826457 0.23147562 0.16025987]
  [0.33333334 0.33333334 0.33333334]]]
[[0 0 0 0]]
[[[1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]
  [1. 0. 0.]]]


In [56]:

d = [[[ 0.5920745,  -0.28320658, -0.5829943 ],
 [ 0.,  0.,  0.],
 [ 0.6626713,  -0.31611645, 0.6807799 ],
 [ 0.6591772,  -0.3069582,  -0.674636  ],
 [ 0.,  0.,  0.],
 [ 0.,  0.,  0.],
 [ 0.,  0.,  0.]]]
e = [[[ 0.5920745,  -0.28320658, -0.5829943 ],
 [ 0.6626713,  -0.31611645, 0.6807799 ],
 [ 0.6591772,  -0.3069582,  -0.674636  ],
 [ 0.,  0.,  0.],
 [ 0.,  0.,  0.],
 [ 0.,  0.,  0.]]]
d[0].index([0,0,0])
d

[[[0.5920745, -0.28320658, -0.5829943],
  [0.0, 0.0, 0.0],
  [0.6626713, -0.31611645, 0.6807799],
  [0.6591772, -0.3069582, -0.674636],
  [0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0]]]

In [47]:
get_one_hot(np.argmax(d[0][:3], axis=-1), 3)
get_one_hot(np.argmax(d[0][1], axis=-1),3)

array([0., 0., 1.])

In [58]:
def get_onehot_type(preds, type):
  # target shape: (1705, 80, 3)
  new_preds = []
  if (type == 'aspect') | (type == 'opinion'):
    for i in range(len(preds)):
      new_preds_i = []
      zero_index = preds[i].index([0,0,0])
      temp_preds = preds[i][:zero_index]
      arg_preds = np.argmax(temp_preds, axis=-1)
      new_preds_i.extend(get_one_hot(arg_preds, 3).tolist())
      new_preds_i.extend(preds[i][zero_index:])
      new_preds.append(new_preds_i)
    return np.array(new_preds)
  elif type == 'sentiment':
    for i in range(len(preds)):
      new_preds_i = []
      for j in range(len(preds[i])):
        if preds[i][j] == [0,0,0]:
          new_preds_i.append([0,0,0])
        else:
          arg_pred = np.argmax(preds[i][j], axis=-1)
          new_preds_i.append(get_one_hot(arg_pred, 3).tolist())
      new_preds.append(new_preds_i)
    return np.array(new_preds)
    # for
get_onehot_type(e, 'opinion')

array([[[1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:

      
for l in ae_labels:
    l = int(l)
    i = 0
    if l == 0 :
        aspect_label.append([1, 0, 0])
        i = 1
    elif l == 1:
        aspect_label.append([0, 1, 0])
    elif l == 2:
        aspect_label.append([0, 0, 1])
    else:
        raise ValueError
    augment_indi_a.append(i)


for l in sa_labels:
            l = int(l)
            if l == 0:
                sentiment_label.append([0, 0, 0])
                sentiment_indi.append(1. if is_testing else 0.) # In testing, we don't know the location of aspect terms.
            elif l == 1:
                sentiment_label.append([1, 0, 0])
                sentiment_indi.append(1.)
            elif l == 2:
                sentiment_label.append([0, 1, 0])
                sentiment_indi.append(1.)
            elif l == 3:
                sentiment_label.append([0, 0, 1])
                sentiment_indi.append(1.)
            elif l == 4:
                sentiment_label.append([0, 0, 0])
                sentiment_indi.append(1. if is_testing else 0.) # Ensure there is no label leakage in testing.
            else:
                raise ValueError

In [4]:
%cd /content/drive/MyDrive/RACL_self
!CUDA_VISIBLE_DEVICES=0 python train_racl_hj.py --task res14 --load 0 

/content/drive/.shortcut-targets-by-id/1tg6xht7UamwA6LK1Pf8GxHN_bBH02xFh/RACL_self

Reuse Word Dictionary & Embedding
-----------------------------------Parameters-----------------------------------
I0603 03:18:55.154336 140392536733568 model_hj.py:38] -----------------------------------Parameters-----------------------------------
>>> model: racl
>>> task: res14
>>> batch_size: 8
>>> learning_rate: 0.0001
>>> global_dim: 300
>>> domain_dim: 100
>>> kp1: 0.5
>>> kp2: 0.5
>>> reg_scale: 1e-05
>>> filter_num: 256
>>> class_num: 3
>>> load: 0
>>> max_sentence_len: 80
>>> n_iter: 10
>>> kernel_size: 3
>>> hop_num: 4
>>> warmup_iter: 5
>>> emb_dim: 400
>>> num_students: 5
>>> unlabeled_ratio: 0.7
>>> shake_ratio: 0.5
>>> data_path: data/res14/
>>> train_path: data/res14/train/
>>> test_path: data/res14/test/
>>> dev_path: data/res14/dev/


I0603 03:18:55.155024 140392536733568 model_hj.py:39] >>> model: racl
>>> task: res14
>>> batch_size: 8
>>> learning_rate: 0.0001
>>> global_dim: 300
>>>

In [14]:
%cd /content/drive/MyDrive/RACL_self
# !CUDA_VISIBLE_DEVICES=0 python train_racl.py --task res14 --load 0 --sup_size 300 --unsup_ratio 8 --consistency_coeff 0 --alpha_sr 0.4 --confidence_thresh 0.7
# !CUDA_VISIBLE_DEVICES=0 python train_racl.py --task res14 --load 0 --sup_size 300 --unsup_ratio 8 --consistency_coeff 0 --alpha_sr 0.4 --confidence_thresh 0.7
# !CUDA_VISIBLE_DEVICES=0 python train_racl.py --task res14 --load 0 --sup_size 300 --unsup_ratio 8 --consistency_coeff 0 --alpha_sr 0.4 --confidence_thresh 0.7
# !CUDA_VISIBLE_DEVICES=0 python train_racl.py --task res14 --load 0 --sup_size 600 --unsup_ratio 8 --consistency_coeff 1 --alpha_sr 0.4 --confidence_thresh 0.7
# !CUDA_VISIBLE_DEVICES=0 python train_racl.py --task res14 --load 0 --sup_size 600 --unsup_ratio 8 --consistency_coeff 1 --alpha_sr 0.4 --confidence_thresh 0.7
!CUDA_VISIBLE_DEVICES=0 python train_racl.py --task res14 --load 0 --sup_size 600 --unsup_ratio 8 --consistency_coeff 1 --alpha_sr 0.4 --confidence_thresh 0.7
# %cd /content/drive/MyDrive/RACL
# !CUDA_VISIBLE_DEVICES=0 python train_racl_a.py --task res14 --load 0

/content/drive/.shortcut-targets-by-id/1tg6xht7UamwA6LK1Pf8GxHN_bBH02xFh/RACL_self
usage: train_racl.py [-h] [--model MODEL] [--task TASK]
                     [--batch_size BATCH_SIZE] [--learning_rate LEARNING_RATE]
                     [--global_dim GLOBAL_DIM] [--domain_dim DOMAIN_DIM]
                     [--kp1 KP1] [--kp2 KP2] [--reg_scale REG_SCALE]
                     [--filter_num FILTER_NUM] [--class_num CLASS_NUM]
                     [--load LOAD]
train_racl.py: error: unrecognized arguments: --sup_size 600 --unsup_ratio 8 --consistency_coeff 1 --alpha_sr 0.4 --confidence_thresh 0.7


In [ ]:
# %env new_task=res14_300
# !python eda_nlp/code/augment.py --input=data/$new_task/unsup/train/sentence.txt --output=data/$new_task/aug/train/sentence.txt --num_aug=1 --alpha_sr=0.2 --alpha_rd=0.0 --alpha_ri=0.0 --alpha_rs=0.0
# !python eda_nlp/code/augment.py --input=data/$new_task/unsup/dev/sentence.txt --output=data/$new_task/aug/dev/sentence.txt --num_aug=1 --alpha_sr=0.2 --alpha_rd=0.0 --alpha_ri=0.0 --alpha_rs=0.0


In [ ]:
# %pip install -U nltk
# !python
# import nltk; nltk.download('wordnet')